name: app
description: "fake store"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  hive: ^2.2.3
  get_it: ^7.7.0
  logger: ^2.5.0
  equatable: ^2.0.7
  injectable: ^2.4.4
  go_router: ^15.1.1
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator:
  freezed: ^2.5.7
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.8.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0


flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: product_sans
      fonts:
        - asset: fonts/product_sans_regular.ttf
          weight: 400
        - asset: fonts/product_sans_medium.ttf
          weight: 500
        - asset: fonts/product_sans_bold.ttf
          weight: 700