name: app
description: "fake store"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  hive: ^2.2.3
  get_it: ^8.0.3
  logger: ^2.5.0
  go_router: ^15.1.1
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
#  freezed: ^3.0.6
  freezed: ^3.0.0-0.0.dev
  json_serializable:
  hive_generator:

flutter:
  uses-material-design: true